version: "3.9"
services:
  lab:
    image: "vitaminic/lab:php81-fpm"
    container_name: lab
    restart: always
    env_file:
      - .env # path to your .env file
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lab.rule=Host(`p-amp-lab.swi.srse.net`)"
      - "traefik.http.services.lab.loadbalancer.server.port=80"
      - "traefik.docker.network=amp-net"
    networks:
      - amp-net
    volumes:
      - ./:/var/www/app
networks:
  amp-net:
    external: true
