version: "3.9"
services:
  lab:
    container_name: amp
    image: lab:latest
    build:
       context: .
       args:
         - phpTag=8.1-fpm
         - nodeTag=18-bullseye
    ports:
      - "8000:80"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./app:/var/www/app
    environment:
      APP_ENV: development