version: "3.9"
services:
  lab:
    container_name: app
    build:
       context: .
       args:
         - phpTag=8.1-fpm
         - nodeTag=18-bullseye
    ports:
      - "8001:80"
    volumes:
      - ./app:/var/www/app
    environment:
      APP_ENV: development